### ISSUE TITLE
multiple alleles at non-selected site

### ISSUE THREAD

**Issue by leslem** [delt0r/msms#16]
I'm simulating a large amount of sequence data under selection from standing variation with the following command:
msms 300 50 -t 6000.000000 -r 8959.991040 1000000 -I 3 100 100 100 -ej 0.005 2 3 -ej 0.00875 3 1 -en 0.0005 1 0.24 -en 0.000875 3 0.077 -en 0.001 2 0.077 -en 0.001 3 0.0125 -en 0.001125 3 0.077 -en 0.00475 2 0.00373 -en 0.004875 2 0.077 -en 0.0075 1 0.03125 -en 0.007625 1 0.24 -en 0.0085 3 0.00294 -en 0.008625 3 0.077 -en 0.0425 1 0.12 -Smark -N 100000 -SI 0.008500 3 0.250000 0.250000 0.250000 -Sc 0 2 20000.000000 0.000000 0.000000 -Sc 0 3 20000.000000 0.000000 0.000000 -Sp 0.500000 -oOC -Smu 0.006000

I've specified the selected site's position as 0.5, but the site that ends up having multiple alleles is not at this position in at least one rep. In the rep I've examined closely, the site at position 0.49156 has alleles 0-9 and a-d while the selected site at 0.5 remains biallelic.

Is this expected behavior? I thought that only the selected site was allowed to have more than two alleles. Or is it possible that the selected site is actually simulated at position 0.49156?

**Comment by delt0r** [comment]
This is not expected behavior generally. can you past/link/include the output. esp the seed value so that i can replicated the issue. Also are you using the latest version? 

It should be noted that the -Smark option is not really "supported" in that it breaks many of the implied contracts with the output and there are issues internally with its implementation. The refactor will make this more of a "core" feature.

**Comment by leslem** [comment]
The output file I generated is too large to post here, so I've put it in my Dropbox and you can access it here:
https://www.dropbox.com/l/jq80RNCZvM8p60usfdsPkc
The issue was in the fifth rep. (Could also have been in subsequent reps, but that's the first one, which caused my parser to fail.)

I was using version 3.2rc build:56, and hadn't realized there was a recent update released. I'm working on testing the same command line in the newest version (build:92), but I've run into a problem with the latest version and my installed version of Java. I'll start another issue for that.

**Comment by leslem** [comment]
I'm still experiencing this issue in the new version I'm using (build 104), but I've finally tracked down the root of the problem. This command line generates so many segregating sites that the positions need a higher precision. 

It's not necessarily that non-selected sites have more than two alleles - it's that non-selected sites will sometimes have the same position (0.5) as the selected site. But this is a bigger problem as it's not restricted to the selected site. For example, in a rep with 9145 segregating sites, there are only 8709 unique positions. 

So the problem is that I need for there to be higher precision in the positions printed out for the segregating sites, such that each site has a unique position. Is this a change that could be made easily?

It appears that ms has the same behavior (only worse - 4 decimal places rather than 5!)

**Comment by delt0r** [comment]
See Issue #18 for how to change the output precision.
