### ISSUE TITLE
Branch length precision

### ISSUE THREAD

**Issue by paula-tataru** [delt0r/msms#18]
When using a large population size, the default decimal format "0.00000" for the branch lengths of the marginal trees does not have high enough precision. 

For example, for the following command
msms 4 2 -T -t 2.4e6 -r 959999.904 10000000 -eG 0 175028.1728 -eN 1.04167e-6 0.00125
several branches have length 0.

An option should be added to specify the desired precision for the outputted trees.

**Comment by delt0r** [comment]
There is the -oFP option for just this reason. The format of this format string is identical to java's DecimalFormat. 
For example:
msms 20 1 -t 1 -T -oFP 0.000000E00

**Comment by paula-tataru** [comment]
Thanks. I have to say that I couldn't find anything about this option in any of the 3 docs (CheatSheet, InternalManual and Manual), so you should consider adding a few lines about it.

**Comment by delt0r** [comment]
You can use msms -help.  Its always the most up to date
and authoritative documentation.

On Wed, May 29, 2013 at 5:48 PM, paula-tataru notifications@github.comwrote:

> Thanks. I have to say that I couldn't find anything about this option in
> any of the 3 docs (CheatSheet, InternalManual and Manual), so you should
> consider adding a few lines about it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/delt0r/msms/issues/18#issuecomment-18626076
> .

## 

I have no special talents. I am only passionately curious.
--Albert Einstein
