### ISSUE TITLE
Smark clarification

### ISSUE THREAD

**Issue by leslem** [delt0r/msms#25]
You've mentioned several bugs related to the Smark option. Could you clarify under which types of models Smark is likely to give incorrect results? Should we stop using Smark entirely until the refactor is out? 

In particular, if a selected site is still segregating in the population, will the alleles at the selected site be correct? Since the selected site would be output under these circumstances anyway, regardless of Smark, I'd hope it would still be outputting correct information.

**Comment by delt0r** [comment]
The selected site has some issues when there is extreme selection or in the bug you reported. However i have reason to believe that the neutral sites are correct. 

The refactor from forever ago should not be much longer.
