### ISSUE TITLE
Variants arise at same position as selected site... -Smark issue?

### ISSUE THREAD

**Issue by leslem** [delt0r/msms#27]
I've finally had time to document this issue https://github.com/delt0r/msms/issues/16 I was experiencing before, where another variant site occurs at the same site as the selected site set by -Sp. It seems to happen in all of the models I've tried, but at a very low frequency. I ran the following command to test it, then parsed through all of the simulated data to pick out the ones that have the problem.

java -jar msms.jar 300 100000 -t 0.600000 -r 0.895104 1000 -I 3 100 100 100 -ej 0.005 2 3 -ej 0.00875 3 1 -en 0.0005 1 0.24 -en 0.000875 3 0.077 -en 0.001 2 0.077 -en 0.001 3 0.0125 -en 0.001125 3 0.077 -en 0.00475 2 0.00373 -en 0.004875 2 0.077 -en 0.0075 1 0.03125 -en 0.007625 1 0.24 -en 0.0085 3 0.00294 -en 0.008625 3 0.077 -en 0.0425 1 0.12 -Smark -N 10000 -SI 0.004650 3 0.250000 0.250000 0.250000 -Sc 0 2 2000.000000 1000.000000 0.000000 -Sp 0.500000 -oOC -Smu 0.000600 -oFP 0.0000

Of the 100,000 reps I simulated, 11 have the duplicate variant positions. 

For example, here's the beginning of the first rep with the issue:
//
segsites: 2
positions: 0.5000 0.5000 
00
08
00
00
00
00
00
00
00
00
00
00
02
00
07
00
00
00
00

A file containing the reps that have the problem can be found here: https://www.dropbox.com/sh/c1atsu234us8y8f/7Vy7Rp9J27

**Comment by delt0r** [comment]
This is simply a rounding issue in the output. 

-oFP "#.######" 

The quotes are to escape the shell
