### ISSUE TITLE
Problems simulating selection in different demes and at different times using an admixture model

### ISSUE THREAD

**Issue by ngarud** [delt0r/msms#29]
Hi Greg

I am having some problems with simulating selection with an admixture demography in MSMS using the -SI option. I will describe it below. Apologies for the length of this email -- I am trying to be as thorough as possible. 

Attached is a figure of the admixture model I am simulating.

![admixturesamplingscheme](https://f.cloud.github.com/assets/2090968/1118404/bf01d12a-1a5d-11e3-9510-3ef520798bb8.png)

I want to simulate selection starting at various times past ward in various demes resulting in the following four scenarios:

1) Selection starting in North America at age=7.2e-05 (this is right after the admixture event)
2) Selection starting in Europe at age=7e-04 (this is right before the admixture event)
3) Selection starting in Africa at age=0.1192000 (this is right after the African bottleneck)
4) Selection starting in Africa at age=0.1192019 (this is during the African bottleneck)

In all of my simulations I draw samples from the North American population only. I print out the allele trajectories in all cases using -oTrace.
This is what I observe:

1) When selection starts at age=7.2e-05 in North America, there are trajectories for three demes, as expected. The time of sampling is at 5.718179187033702E-5 for a particular run, and the partial frequency of the sweep in the North American deme is 1.0.

2) When selection starts at age=7e-04 in Europe, there are trajectories for four demes, but the time of sampling is always at 7.265805891432982E-5, which is right when the admixture event happens. I don't understand why this is happening if I want to sample in North America at time zero.

Furthermore, the partial frequency of the adaptive allele in North America mysteriously jumps from 0 to 1 in 1 generation (these are the last two lines of the trajectory):
7.270830653460252E-5    0.0     1.0     0.0     1.0     1.0     0.0     1.0     0.0
7.265805891432982E-5    0.0     1.0     0.0     1.0     0.0     1.0     0.0     1.0

3) I have a similar problem when I start selection at age=0.1192000 in Africa. Sampling occurs at the time of admixture, and the partial frequency jumps from 0 to 1 in one generation.
7.270830653460252E-5    0.0     1.0     0.0     1.0     1.0     0.0     1.0     0.0
7.265805891432982E-5    0.0     1.0     0.0     1.0     0.0     1.0     0.0     1.0

4) For some strange reason, when I start selection even further pastward in Africa at age=0.1192019, I am able to sample in North America at time=5.848822999742732E-5  and the number of demes with trajectories changes from 4 to 3 as the model changes from pre to post admixture.

I used your work around for the -es and -ej options that you had sent me earlier, as I was earlier having trouble starting selection before admixture.

Here is the code for the four different models that I am using:
# fixed parameters

Nac=4975360
mu=10^-9
locusLength=8000
theta=1592.12
s=995072
s2=1990144
smu=50
rho=796.058

totalSampleSize=145
numberOfSimulations=1
sampleSizeAfrica=0
sampleSizeEurope=0
sampleSizeAmerica=145
scaledNeEurope=0.6276
growthRateEurope=-2.674174e-05
scaledNeAmerica=3.2127
growthRateAmerica=-0.006059296
scaledTimeAdmixture=7.263e-05
scaledTimeAdmixture2=7.264e-05
proportionAdmixture=0.85
scaledTimeSplitAfricaEurope=0.009798
scaledTimeAfricaExpansion=0.1192009
scaledNeAfricaBottleneck=0.0001246
scaledTimeAfricaCrash=0.1192512
scaledNeAfricaAncestral=1.049994

Model 1)

age=7.2e-05

./msms/bin/msms  $totalSampleSize $numberOfSimulations -N $Nac -t $theta -I 3 $sampleSizeAfrica $sampleSizeEurope $sampleSizeAmerica -n 2 $scaledNeEurope -g 2 $growthRateEurope -n 3 $scaledNeAmerica -g 3 $growthRateAmerica -es $scaledTimeAdmixture 3 $proportionAdmixture -ej $scaledTimeAdmixture2 3 2 -ej $scaledTimeAdmixture2 4 1 -ej $scaledTimeSplitAfricaEurope 2 1 -en $scaledTimeAfricaExpansion 1 $scaledNeAfricaBottleneck -en $scaledTimeAfricaCrash 1 $scaledNeAfricaAncestral -r $rho $locusLength -SAA $s2 -SaA $s -SI $age 3 0 0 3.128062e-08 -SFC -Smu $smu -Sp 0.5 -oTrace
# here is the code with the variables substituted in

./msms/bin/msms 145 1 -N 4975360 -t 1592.12 -I 3 0 0 145 -n 2 0.6276 -g 2 -2.674174e-05 -n 3 3.2127 -g 3 -0.006059296 -es 7.263e-05 3 0.85 -ej 7.264e-05 3 2 -ej 7.264e-05 4 1 -ej 0.009798 2 1 -en 0.1192009 1 0.0001246 -en 0.1192512 1 1.049994 -r 796.058 8000 -SAA 1990144 -SaA 995072 -SI 7.2e-05 3 0 0 3.128062e-08 -SFC -Smu 50 -Sp 0.5 -oTrace

Model 2)
./msms/bin/msms 145 1 -N 4975360 -t 1592.12 -I 3 0 0 145 -n 2 0.6276 -g 2 -2.674174e-05 -n 3 3.2127 -g 3 -0.006059296 -es 7.263e-05 3 0.85 -ej 7.264e-05 3 2 -ej 7.264e-05 4 1 -ej 0.009798 2 1 -en 0.1192009 1 0.0001246 -en 0.1192512 1 1.049994 -r 796.058 8000 -SAA 1990144 -SaA 995072 -SI 7e-04 4 0 5.888435e-05 0 0 -SFC -Smu 50 -Sp 0.5 -oTrace
Model 3)
./msms/bin/msms 145 1 -N 4975360 -t 1592.12 -I 3 0 0 145 -n 2 0.6276 -g 2 -2.674174e-05 -n 3 3.2127 -g 3 -0.006059296 -es 7.263e-05 3 0.85 -ej 7.264e-05 3 2 -ej 7.264e-05 4 1 -ej 0.009798 2 1 -en 0.1192009 1 0.0001246 -en 0.1192512 1 1.049994 -r 796.058 8000 -SAA 1990144 -SaA 995072 -SI 0.1192000 4 0.0008065429 0 0 0 -SFC -Smu 50 -Sp 0.5 -oTrace

Model 4)
./msms/bin/msms 145 1 -N 4975360 -t 1592.12 -I 3 0 0 145 -n 2 0.6276 -g 2 -2.674174e-05 -n 3 3.2127 -g 3 -0.006059296 -es 7.263e-05 3 0.85 -ej 7.264e-05 3 2 -ej 7.264e-05 4 1 -ej 0.009798 2 1 -en 0.1192009 1 0.0001246 -en 0.1192512 1 1.049994 -r 796.058 8000 -SAA 1990144 -SaA 995072 -SI 0.1192019 4 0.0008065429 0 0 0 -SFC -Smu 50 -Sp 0.5 -oTrace

Thank you,
Nandita

**Comment by delt0r** [comment]
Sorry this has taken so long. 

The last time of the trace is _not_ the sampling time. It is the time that selection is switched off. However the selected allele is in an absorbing state, that is fixed in the population. This is not properly detected and it proceeds continue with the forward simulation for far longer than it should. Of course if its fixed in an ancestral population then it must be fixed in all subsequent populations.  

Other than being slow, and the trace running for too long, the results should be correct.
