### ISSUE TITLE
Hangs with -SFC

### ISSUE THREAD

**Issue by ChristianHuber** [delt0r/msms#3]
I condition on the beneficial mutation not being lost (-SFC). The code works fine if the mutation starts at time 0.7 (with frequency 0.05), but stops working when the mutation starts at time 0.8 (or later). 

msms -ms 177 1 -t 454 -r 91 -I 2 128 49 0 -n 1 1.662640 -n 2 1.305640 -eg 0 1 0.944534 -ma x 0.361398 1.264478 x -en 0.001797 2 0.103324 -eg 0.001797 2 9.138135 -ej 1.936972 2 1 -en 1.936972 1 1 -N 10000.0 -SFC -SI 0.8 2 0.0 0.0001 -Sc 0 2 500.0 -Sp 0.5

Output:
ms 177 1 -t 454 -r 91 -I 2 128 49 0 -n 1 1.662640 -n 2 1.305640 -eg 0 1 0.944534 -ma x 0.361398 1.264478 x -en 0.001797 2 0.103324 -eg 0.001797 2 9.138135 -ej 1.936972 2 1 -en 1.936972 1 1 -N 10000.0 -SFC -SI 0.8 2 0.0 0.05 -Sc 0 2 500.0 -Sp 0.5  [3.2rc Build:74]
0xffa8ced49b83cb15

**Comment by Schoki95** [comment]
I have a similar issue with the -SFC switch. For 7 out of 200 cases the selected site is lost although I was using the -SFC switch. Here are the 3 command lines (including the seeds that were used) where the allele was lost:
1. ms 50 100 -N 10000 -t 18.6377346873398 -r 0 1000 -I 2 25 25 -m 1 2 2.09398466442933 -m 2 1 2.09398466442933 -n 2 0.116885667357303 -ej 7.42244228599473 2 1 -Sp 0.5 -SA 91.0921753634219 -SI 7.42244228599473 2 0 0.000855536887121616 -SFC -eN 7.42244228599473 1.3 -g 2 -0.126991384154586 -seed 208399 -Smark  [3.2rc Build:74]
2. ms 50 100 -N 10000 -t 8.66519856946281 -r 7.39159373869188 1000 -I 2 25 25 -m 1 2 0.206473152251038 -m 2 1 0.206473152251038 -n 2 1.9881238872371 -ej 10.9398455064773 2 1 -Sp 0.5 -SA 1.40271588939969 -SI 10.9398455064773 2 0 5.02986763762345e-05 -SFC -eN 10.9398455064773 1.3 -g 2 0.17286937251743 -seed 350712 -Smark  [3.2rc Build:74]
3. ms 50 100 -N 10000 -t 6.84858108046949 -r 0 1000 -I 2 25 25 -m 1 2 1.16287482325675 -m 2 1 1.16287482325675 -n 2 0.23495818340833 -ej 8.92275093698072 2 1 -Sp 0.5 -SA 387.926165971333 -SI 8.92275093698072 2 0 0.000425607648771321 -SFC -eN 8.92275093698072 1.3 -g 2 -0.0273878449611568 -seed 471831 -Smark  [3.2rc Build:74]

Thanks in advance for helping!

**Comment by delt0r** [comment]
It should be noted that in time ranges population sizes are smaller than 1!
