### ISSUE TITLE
Beneficial allele gets lost although -SFC is set

### ISSUE THREAD

**Issue by ChristianHuber** [delt0r/msms#30]
There are some cases where the beneficial allele gets lost although -SFC is set.

F.e.
msms -seed 1234 -ms 177 1 -t 0 -r 0 -I 2 128 49 0 -n 1 1.655290 -n 2 0.168389 -ma x  2.451840 11.804420 x -ema 0.078107 2 x 0 0 x -ej 0.308381 2 1 -en 0.308381 1 1 -NC -N 10000 -SFC -SI 0.08 2 3.02061874354343e-05 0 -Sc 0 -1 50 -Sp 0.5 -oTrace

The last entry of the trace indicates that the allele frequency has reached zero in both populations at time 0. Shouldn't -SFC prevent that?

**Comment by delt0r** [comment]
Fixed in next release...
