### ISSUE TITLE
Strange output when using -Smark and -SI together

### ISSUE THREAD

**Issue by ksiewert** [delt0r/msms#37]
I am using MSMS to simulate selection on standing variation and am getting strange behavior when I use the -Smark option together with the -SI option. Here is an command line I gave:
msms 100 1000 -t 1.0 -Smark -N 10000 -SI .01 1 .3 -SAA 200 -SaA 200

There were not any errors messages, and everything seemed normal, except in addition to having 0's and 1's for the state of the selected state, it also had numbers other than 0 or 1 and letters. For example, here is the beginning of the output:
//
segsites: 7
positions: 0.00000 0.04883 0.16482 0.22270 0.83575 0.93057 0.98100
k000000
0000011
l010100
0000000
t000100
9000000
p010100
c000011
s100011
0000011
t000100
s100011
q000000
0000011
n000011
q000000
j100011
t000100
a000011
p010100
2000011
0000011
e000000
i000000
2000011
l010100
s100011
p010100
0100011
9000000

I do not get this error if I don't use the -Smark or -SI at the same time. Is this intentional (I couldn't find any mention of it in the manual) or could it be a bug?

Thank you!

**Comment by delt0r** [comment]
This is expected behavior. This means there are many origins of the beneficial allele. So the first one is 1 the second a 2 etc. it uses a full radix 36 number.
