### ISSUE TITLE
out of memory using -oTrace option

### ISSUE THREAD

**Issue by ngarud** [delt0r/msms#9]
I can't seem to use the -oTrace option, even when I increase the amount of memory Java can use. I'm running a complex admixture model with selection. I can run the model with selection when I do not use -oTrace, and I can also run a simpler demographic model with selection with the -oTrace command. 

Thanks for your help.

**Comment by delt0r** [comment]
generally a command line helps. Though others have submitted the same issue. It would be nice if I can double check to ensure that i also fix this particular case.
